name: Terraform Demo
on: push
jobs:
    Helloworld:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: List Down Content
              run: ls -al

            # - name: Configure AWS credentials from Test account
            #   uses: aws-actions/configure-aws-credentials@v3
            #   with:
            #     role-to-assume: arn:aws:iam::111111111111:role/my-github-actions-role-test
            #     aws-region: us-east-1

            # - name: Configure AWS credentials from Test account
            #   uses: aws-actions/configure-aws-credentials@v4
            #   with:
            #     aws-region: ap-south-1  # Replace with your desired AWS region
            #     role-to-assume: arn:aws:iam::227390912900:role/GitTerraformRole  # Replace with the ARN of your Terraform role

            - name: Configure AWS Manually
              run: |
               curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

            - name: unzip
              run: unzip awscliv2.zip
            
            - name: install aws cli
              run: ls -al

            - name: PWD
              run: pwd
      
            - name: Print Hello World
              run: echo "Hello, World!"