name: Terraform Demo
on: workflow_dispatch
jobs:
    Helloworld:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: List Down Content
              run: ls -al

            - name: Download Backend.tf 
              run: wget https://file-access-by-ayush.s3.ap-south-1.amazonaws.com/backend.tf?${{ secrets.BUCKET }}

            - name: List the backend.tf
              run: cat backend.tf
      
            - name: Print Hello World
              run: echo "Hello, World!"