name: Terraform Demo
on: 
  push:
    branches:
      - 'master'
  issue_comment:
    types: [created]
permissions:
  id-token: write #this is imp to set the token as not have this will not allow to set assumed role
  contents: read
  pull-requests: write




jobs:
    Commented:
      name: PR comment
      if: ${{ github.event.issue.pull_request && (github.event.comment.body == 'tf plan' || github.event.comment.body == 'tf apply') && github.event.action != 'closed'}}
      env: 
        NUMBER: ${{ github.event.issue.number }}
        AWS_REGION: ap-south-1
      runs-on: ubuntu-latest
      steps:
        - name: Print PR Number 
          run: echo "A comment on PR $NUMBER"
      
        - name: Checkout
          uses: actions/checkout@v3
          with:
            ref: "refs/pull/${{ env.NUMBER }}/merge"

        - name: Configure
          uses: aws-actions/configure-aws-credentials@v3
          with:
            role-to-assume: ${{ secrets.ASSUMED_ROLE }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Configure Backend
          run: aws s3 cp s3://file-access-by-ayush/backend.tf backend.tf
  
        - name: Terraform Init
          run: terraform init
            
        - name: Terraform Plan
          if: ${{ github.event.comment.body == 'tf plan' }}
          run: terraform plan

        - name: Terraform Apply
          if: ${{ github.event.comment.body == 'tf apply' }}
          run: terraform apply --auto-approve
    Testing:
      runs-on: ubuntu-latest
      steps:
        - name: Print Github Object
          run: echo "Printing ${{ toJson(github) }}"